<?php
/* Accordion Post Type */
$labels = array(
	'name'                  => _x( 'Accordions', 'Post Type General Name', 'wp-accordions' ),
	'singular_name'         => _x( 'Accordion', 'Post Type Singular Name', 'wp-accordions' ),
	'menu_name'             => __( 'Accordions', 'wp-accordions' ),
	'name_admin_bar'        => __( 'Accordion', 'wp-accordions' ),
	'archives'              => __( 'Accordion Archives', 'wp-accordions' ),
	'attributes'            => __( 'Accordion Attributes', 'wp-accordions' ),
	'parent_item_colon'     => __( 'Parent Accordion:', 'wp-accordions' ),
	'all_items'             => __( 'All Accordions', 'wp-accordions' ),
	'add_new_item'          => __( 'Add New Accordion', 'wp-accordions' ),
	'add_new'               => __( 'Add New', 'wp-accordions' ),
	'new_item'              => __( 'New Accordion', 'wp-accordions' ),
	'edit_item'             => __( 'Edit Accordion', 'wp-accordions' ),
	'update_item'           => __( 'Update Accordion', 'wp-accordions' ),
	'view_item'             => __( 'View Accordion', 'wp-accordions' ),
	'view_items'            => __( 'View Accordions', 'wp-accordions' ),
	'search_items'          => __( 'Search Accordion', 'wp-accordions' ),
	'not_found'             => __( 'Not found', 'wp-accordions' ),
	'not_found_in_trash'    => __( 'Not found in Trash', 'wp-accordions' ),
	'featured_image'        => __( 'Featured Image', 'wp-accordions' ),
	'set_featured_image'    => __( 'Set featured image', 'wp-accordions' ),
	'remove_featured_image' => __( 'Remove featured image', 'wp-accordions' ),
	'use_featured_image'    => __( 'Use as featured image', 'wp-accordions' ),
	'insert_into_item'      => __( 'Insert into item', 'wp-accordions' ),
	'uploaded_to_this_item' => __( 'Uploaded to this item', 'wp-accordions' ),
	'items_list'            => __( 'Accordions list', 'wp-accordions' ),
	'items_list_navigation' => __( 'Accordions list navigation', 'wp-accordions' ),
	'filter_items_list'     => __( 'Filter items list', 'wp-accordions' ),
);
$args = array(
	'label'                 => __( 'Accordion', 'wp-accordions' ),
	'description'           => __( 'Accordion Text', 'wp-accordions' ),
	'labels'                => $labels,
	'supports'              => array( 'title', 'editor' ),
	'hierarchical'          => false,
	'public'                => false,
	'show_ui'               => true,
	'show_in_menu'          => true,
	'menu_position'         => 5,
	'menu_icon'             => 'dashicons-editor-justify',
	'show_in_admin_bar'     => true,
	'show_in_nav_menus'     => true,
	'can_export'            => true,
	'has_archive'           => false,
	'exclude_from_search'   => true,
	'publicly_queryable'    => false,
);
register_post_type( 'wp-accordions', $args );
?>